# Generated by Django 5.1.2 on 2024-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('Alimento', 'Alimento'), ('Eletronicos', 'Eletronicos'), ('Estacionario', 'Estacionario')], max_length=20, null=True),
        ),
    ]
