# Generated by Django 5.1.5 on 2025-01-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('Eletronicos', 'Eletronicos'), ('Alimento', 'Alimento'), ('Estacionario', 'Estacionario')], max_length=20, null=True),
        ),
    ]
